---
language: php
php:
  - 7.1

branches:
  only:
    - master
    - /^test\/.*$/

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: travis_retry composer update --prefer-dist

script:
  # PHP CS Fixer
  - CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")
  - if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php_cs(\\.dist)?|composer\\.lock)$"; then IFS=$'\n' EXTRA_ARGS=('--path-mode=intersection' '--' ${CHANGED_FILES[@]}); fi
  - vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --stop-on-violation --using-cache=no "${EXTRA_ARGS[@]}"

  # phpSpec
  - vendor/bin/phpspec run -f progress

notifications:
  slack:
    rooms:
      secure: "FUlZBcgfHiSl6dpeEkVsIL8M6OMbh8k6WTbSUeaCVQUqU+ISYWpTyz+weiL+2g4Z9vPE9Q+hrdLdC/Pb+X4HMywo/Ku3jdJCvY07bEm8YW3Ifr5461J2sFvvj1OsyKUHZiJzFPJCVK1TkFKWsDquADcm+SEUgKcYjJw71RZQv4u9oeg/Fb38xHSHLHFO6dUv+pCAJukKNPsgVDj2gj3HQXI6aroNsdKM5euaIYSHDZ4aRaxXJ9w2evgr1PeCVjYITwB+pvZCvAnrnLu+pItNvpC2+on93dpy6b29mr+zvUAT7nNSYoX+AfKUDZemOrjlzpqqJAR7+74k4K4x7tDeYNGp9AV2eYWd5I28af125q94k0eMjfxVVGUFClpibuuTUUPdlgcw5nY+QeTuM4KL6L563s8ZcApwH7vbf99vUH4po/wkqJlm8z37PktoZaU80oj+Sdr5BCpQ0lNrB2TuUl4gm7LurBGP7g1Gd18LUByrsvLMAi97rgGIlqc/6UjF7gzSLnHRF9jfvZIxfxSDtPHwCG2N2fEoUY1bpkmymIgUmjpQOShgRJpllZEXZYl1H5kfLco6nw+hhorjqr3Rlo8At9MT7gLeMqiGx77UoBlJORk7a/rDY8nMgp4kOLQtdffTey+Tf6ro6DAY/8Bsmx32E8T8H5JBWUPD67lsJkM="
    on_success: change
    on_failure: always
